import { Monitor, Smartphone, XpsLaptop, IPhone } from '../imgs';
export default [
  {
    id:0,
    label: 'Surface laptop 3',
    imgSrc: Monitor,
    price: 1,
    key: 'Monitors',
  },
  {
    id:1,
    label: 'XPS laptop 13',
    imgSrc: Smartphone,
    price: 2,
    key: 'Smartphone',
  },
  {
    id:2,
    label: 'LG Gram 17',
    imgSrc: XpsLaptop,
    price: 3,
    key: 'Laptops',
  },
  {
    id:3,
    label: 'Macbook pro 13',
    imgSrc: Smartphone,
    price: 4,
    key: 'Columns',
  },
  {
    id:4,
    label: 'Phone',
    imgSrc: Monitor,
    price: 5,
    key: 'Phone',
  },
  {
    id:5,
    label: 'Note',
    imgSrc: Smartphone,
    price: 6,
    key: 'Note',
  },
  {
    id:6,
    label: 'Monitors',
    imgSrc: Monitor,
    price: 7,
    key: 'Monitors2',
  },
  {
    id:7,
    label: 'Smartphone',
    imgSrc: Smartphone,
    price: 8,
    key: 'Smartphone2',
  },
  {
    id:8,
    label: 'Laptops',
    imgSrc: XpsLaptop,
    price: 9,
    key: 'Laptops2',
  },
  {
    id:9,
    label: 'Columns',
    imgSrc: Smartphone,
    price: 10,
    key: 'Columns2',
  },
  {
    id:10,
    label: 'Phone',
    imgSrc: IPhone,
    price: 11,
    key: 'Phone2',
  },
  {
    id:11,
    label: 'Note',
    imgSrc: IPhone,
    price: 12,
    key: 'Note2',
  },
];
